"""
@author : Shrikanth N C (nc.shrikanth@gmail.com)
Date: 15 Dec 2019
Script to assess belief 1 Corbat ́o’s law
License: See LICENSE file
"""

from data.pspdata import *
import math


MINIMUM_SAMPLE_SIZE = 50
MAX_SAMPLE_SIZE = math.inf #100


PROGRAM_ASSIGNMENT_LIST_ALL = [ str(x)+'A' for x in range(1,11)]

PROGRAM_ASSIGNMENT_LIST_LEVEL0 = [ str(x)+'A' for x in range(1,4)]
PROGRAM_ASSIGNMENT_LIST_LEVEL1 = [ str(x)+'A' for x in range(4,7)]
PROGRAM_ASSIGNMENT_LIST_LEVEL2 = [ str(x)+'A' for x in range(7,11)]

PROGRAMMING_LANGUAGES = ['C', 'C++', 'C#', 'JAVA', 'VB']


STATSCOURSE_COLNAME  =  'StatsCourse'
PROGRAMMINGLANGUAGE_COLNAME  =  'ProgrammingLanguage'
YEARSPROGRAMMINGEXPERIENCE_COLNAME  =  'YearsProgrammingExperience'
PSPASSGTDATAID_COLNAME  =  'PSPAssgtDataID'
PSPSTUDATAID_COLNAME  =  'PSPStuDataID'
ASSGTSTATUSID_COLNAME  =  'AssgtStatusID'
PSPLEVEL_COLNAME  =  'PSPLevel'
ASSGTSEQUENCE_COLNAME  =  'AssgtSequence'
PROGRAMASSIGNMENT_COLNAME  =  'ProgramAssignment'
ESTLOC_COLNAME  =  'EstLOC'
ACTLOC_COLNAME  =  'ActLOC'
ESTMIN_COLNAME  =  'EstMin'
ACTMIN_COLNAME  =  'ActMin'
ESTDEFREM_COLNAME  =  'EstDefRem'
ACTDEFREM_COLNAME  =  'ActDefRem'
ESTMINPLAN_COLNAME  =  'EstMinPlan'
ACTMINPLAN_COLNAME  =  'ActMinPlan'
ESTMINDSGN_COLNAME  =  'EstMinDsgn'
ACTMINDSGN_COLNAME  =  'ActMinDsgn'
ESTMINDLDR_COLNAME  =  'EstMinDLDR'
ACTMINDLDR_COLNAME  =  'ActMinDLDR'
ESTMINCODE_COLNAME  =  'EstMinCode'
ACTMINCODE_COLNAME  =  'ActMinCode'
ESTMINCR_COLNAME  =  'EstMinCR'
ACTMINCR_COLNAME  =  'ActMinCR'
ESTMINCOMPILE_COLNAME  =  'EstMinCompile'
ACTMINCOMPILE_COLNAME  =  'ActMinCompile'
ESTMINTEST_COLNAME  =  'EstMinTest'
ACTMINTEST_COLNAME  =  'ActMinTest'
ESTMINPM_COLNAME  =  'EstMinPM'
ACTMINPM_COLNAME  =  'ActMinPM'
ESTDEFINJPLAN_COLNAME  =  'EstDefInjPlan'
ESTDEFINJDSGN_COLNAME  =  'EstDefInjDsgn'
ESTDEFINJDLDR_COLNAME  =  'EstDefInjDLDR'
ESTDEFINJCODE_COLNAME  =  'EstDefInjCode'
ESTDEFINJCR_COLNAME  =  'EstDefInjCR'
ESTDEFINJCOMPILE_COLNAME  =  'EstDefInjCompile'
ESTDEFINJTEST_COLNAME  =  'EstDefInjTest'
ESTDEFREMPLAN_COLNAME  =  'EstDefRemPlan'
ESTDEFREMDSGN_COLNAME  =  'EstDefRemDsgn'
ESTDEFREMDLDR_COLNAME  =  'EstDefRemDLDR'
ESTDEFREMCODE_COLNAME  =  'EstDefRemCode'
ESTDEFREMCR_COLNAME  =  'EstDefRemCR'
ESTDEFREMCOMPILE_COLNAME  =  'EstDefRemCompile'
ESTDEFREMTEST_COLNAME  =  'EstDefRemTest'
ACTDEFINJPLAN_COLNAME  =  'ActDefInjPlan'
ACTDEFINJDSGN_COLNAME  =  'ActDefInjDsgn'
ACTDEFINJDLDR_COLNAME  =  'ActDefInjDLDR'
ACTDEFINJCODE_COLNAME  =  'ActDefInjCode'
ACTDEFINJCR_COLNAME  =  'ActDefInjCR'
ACTDEFINJCOMPILE_COLNAME  =  'ActDefInjCompile'
ACTDEFINJTEST_COLNAME  =  'ActDefInjTest'
ACTDEFREMPLAN_COLNAME  =  'ActDefRemPlan'
ACTDEFREMDSGN_COLNAME  =  'ActDefRemDsgn'
ACTDEFREMDLDR_COLNAME  =  'ActDefRemDLDR'
ACTDEFREMCODE_COLNAME  =  'ActDefRemCode'
ACTDEFREMCR_COLNAME  =  'ActDefRemCR'
ACTDEFREMCOMPILE_COLNAME  =  'ActDefRemCompile'
ACTDEFREMTEST_COLNAME  =  'ActDefRemTest'
DDTEST_COLNAME  =  'DDTest'
ACTPRODRATE_COLNAME  =  'ActProdRate'
RELSIZEERROR_COLNAME  =  'RelSizeError'
ABSRELSIZEERROR_COLNAME  =  'absRelSizeError'
RELEFFORTERROR_COLNAME  =  'RelEffortError'
ABSRELEFFORTERROR_COLNAME  =  'absRelEffortError'
ACTMINPROD_COLNAME  =  'ActMinProd'
ESTMINOH_COLNAME  =  'EstMinOH'
ESTMINCONST_COLNAME  =  'EstMinConst'
ESTMINAPR_COLNAME  =  'EstMinApr'
ESTMINFAIL_COLNAME  =  'EstMinFail'
ACTMINOH_COLNAME  =  'ActMinOH'
ACTMINCONST_COLNAME  =  'ActMinConst'
ACTMINAPR_COLNAME  =  'ActMinApr'
ACTMINFAIL_COLNAME  =  'ActMinFail'
CONSTPRODRATIO_COLNAME  =  'ConstProdRatio'
APRPRODRATIO_COLNAME  =  'AprProdRatio'
FAILPRODRATIO_COLNAME  =  'FailProdRatio'
RATIO_DSGNCODE_COLNAME  =  'Ratio_DsgnCode'
RATIO_CRCODE_COLNAME  =  'Ratio_CRCode'
RATIO_DLDRDSGN_COLNAME  =  'Ratio_DLDRDsgn'
RATIO_APRCONST_COLNAME  =  'Ratio_AprConst'
DDCOMPILE_COLNAME  =  'DDCompile'
RATECR_COLNAME  =  'RateCR'
DEFESCDSGN_COLNAME  =  'DefEscDsgn'
DEFESCDLDR_COLNAME  =  'DefEscDLDR'
DEFESCCODE_COLNAME  =  'DefEscCode'
DEFESCCR_COLNAME  =  'DefEscCR'
DEFESCCOMPILE_COLNAME  =  'DefEscCompile'
YIELDDLDR_COLNAME  =  'YieldDldr'
YIELDCR_COLNAME  =  'YieldCR'
YIELDCOMPILE_COLNAME  =  'YieldCompile'
PROCESSYIELD_COLNAME  =  'ProcessYield'
DEFREMRATEDLDR_COLNAME  =  'DefRemRateDLDR'
DEFREMRATECR_COLNAME  =  'DefRemRateCR'
DEFREMRATECOMPILE_COLNAME  =  'DefRemRateCompile'
DEFREMRATETEST_COLNAME  =  'DefRemRateTest'
DEVELOPER_LOC_COLNAME  =  'Developer LOC'
DEVELOPERCONSTMIN_COLNAME  =  'DeveloperConstMin'
DEVELOPERPRODMIN_COLNAME  =  'DeveloperProdMin'
DEVELOPERPRODRATE_COLNAME  =  'DeveloperProdRate'
DEVELOPERDEFECTS_COLNAME  =  'DeveloperDefects'
DEVELOPERTESTDEFECTS_COLNAME  =  'DeveloperTestDefects'
DEVELOPERDD_COLNAME  =  'DeveloperDD'
DEVELOPERDEFINJRATE_COLNAME  =  'DeveloperDefInjRate'
CALC_ACTDEFINJ_COLNAME  =  'Calc_ActDefInj'
CALC_ACTDEFREM_COLNAME  =  'calc_ActDefRem'
MATCH_DEFREM_INJ_COLNAME  =  'Match_DefRem_Inj'
PL_GEN_COLNAME  =  'PL_Gen'
PL_CATEGORY_COLNAME  =  'PL_Category'
ONED_CATEGORY_COLNAME  =  '1D_Category'
PL_LEVEL_COLNAME  =  'PL_Level'
PL_LEVEL_BIN_COLNAME  =  'PL_Level_Bin'
LOC_MIN_COLNAME  =  'LOC/Min'
TASK_COLNAME  =  'Task'


def normalize(samples, minVal, maxVal):



    normCol = []

    for v in samples:

        normalizedValue = (v - minVal) / ((maxVal - minVal) + 0.000000001)

        normCol.append(normalizedValue * 100)


    return normCol



# if __name__ == '__main__':
#
#     df = getPSPDF()
#
#     for c in df.columns:
#         print(c.upper()+"_COLNAME", " = ", "'"+c+"'")